### ISSUE TITLE
Merit reputation gem not hitting second tier routes

### ISSUE THREAD

**Issue by top1select** [merit-gem/merit#248] opened 2016-03-16 19:07 UTC
I'm trying to integrate Merit reputation gem into my existing Rails apps, and have some questions about one rule not hitting Rails routes.

**person.rb**

    class Person < ActiveRecord::Base
      has_merit

    has_many :listings, -> { where(deleted: 0) }, :dependent => :destroy, :foreign_key => "author_id"

**listing.rb**

    class Listing < ActiveRecord::Base
      has_merit

I have two rules in Merit::PointRulesMethods,

**point_rules.rb**

This one is working perfectly,

      score 1, :on => 'people#create', model_name: 'Person', to: :itself

But not this, it's just not working w/o any error messages:

      score 1, :on => 'people/listings#create', model_name: 'Listing', to: :itself

What's the right way to define the second rule?

Many thanks!

**Comment by tute** [comment] 2016-03-17 00:04
Can you paste the relevant content of your routes file please?

**Comment by top1select** [comment] 2016-03-17 00:54
Sure, the first rule works, but the other four not working.

`module Merit
  class PointRules
    include Merit::PointRulesMethods

    def initialize

      score 1, :on => 'people#create', model_name: 'Person', to: :itself

      score 1, :on => 'listings#create', model_name: 'Person', to: :author_id
      score 1, :on => 'listings#create', model_name: 'Listing', to: :author_id

      score 1, :on => 'listings#create', model_name: 'Person', to: :action_user
      score 1, :on => 'listings#create', model_name: 'Listing', to: :action_user

    end
  end
end
`

**Comment by top1select** [comment] 2016-03-17 01:00
It seems the following query is wrong, the id 120 is the listing id, it should be the author_id or action_user.

SELECT  `people`.* FROM `people` WHERE `people`.`id` = '120'

`  Merit::Action Load (0.4ms)  SELECT `merit_actions`.* FROM `merit_actions` WHERE `merit_actions`.`processed` = 0
   (0.1ms)  BEGIN
  SQL (0.3ms)  UPDATE `merit_actions` SET `processed` = 1, `updated_at` = '2016-03-17 00:58:18' WHERE `merit_actions`.`id` = 24
   (1.3ms)  COMMIT
  Person Load (0.3ms)  SELECT  `people`.* FROM `people` WHERE `people`.`id` = '120' LIMIT 1
  CACHE (0.0ms)  SELECT  `people`.* FROM `people` WHERE `people`.`id` = '120' LIMIT 1  [["id", 120]]
[merit] Couldn't find model to grant reputation to. Refer to https://github.com/tute/merit/issues/171#issuecomment-44185696.
  CACHE (0.0ms)  SELECT  `people`.* FROM `people` WHERE `people`.`id` = '120' LIMIT 1  [["id", 120]]
  Person Load (0.3ms)  SELECT  `people`.* FROM `people` WHERE `people`.`id` = '0' LIMIT 1
[merit] no Person found with id 0
`

**Comment by tute** [comment] 2016-03-17 01:02
Can you post the `config/routes.rb` file? Do you have this code publicly available?

**Comment by top1select** [comment] 2016-03-17 01:04
It did capture the author_id though:

![image](https://cloud.githubusercontent.com/assets/3697248/13833275/7fcdfc1e-eba1-11e5-9928-3c48ac000cf3.png)

**Comment by top1select** [comment] 2016-03-17 01:05
Here you go!

https://github.com/sharetribe/sharetribe/tree/master/config

**Comment by tute** [comment] 2016-03-17 01:07
You've got quite some routes! Can you paste the output of the `rake routes` command please?

**Comment by top1select** [comment] 2016-03-17 01:12
Yup, below is the relative part, I removed a lot of junk...

POST     (/:locale)/:person_id/listings(.:format)    listings#create 
POST     (/:locale)/listings(.:format)               listings#create

**Comment by tute** [comment] 2016-03-17 01:14
One issue I see is that it's not `people/listings#create` the route you want, but something like `(\d)+/listings#create`.

**Comment by tute** [comment] 2016-03-17 01:15
So it would be:

```ruby
score 1, on: /\d+\/listings\#create/, model_name: 'Listing', to: :itself
```

**Comment by top1select** [comment] 2016-03-17 01:16
I see, how about this route, what should be the rule for it?

close_person_listing PUT      (/:locale)/:person_id/listings/:id/close(.:format)     listings#close

**Comment by tute** [comment] 2016-03-17 01:17
It would be similar to:
```ruby
score 1, on: /\d+\/listings\/\d+\/close#update/
```

**Comment by top1select** [comment] 2016-03-17 01:20
I tried, but this one did not do anything, no merit_action record generated

     score 1, on: /\d+\/listings\#create/, model_name: 'Listing', to: :itself

**Comment by tute** [comment] 2016-03-17 01:23
Can you post the entire log for that action, where you would expect to see the SQL INSERT?

**Comment by top1select** [comment] 2016-03-17 01:30
Ok, for this rule, the log is:


score -1, :on => 'listings#close', model_name: 'Person', to: :author_id



 CommunityCustomization Load (0.4ms)  SELECT  `community_customizations`.* FROM `community_customizations` WHERE `community_customizations`.`community_id` = 1 AND `community_customizations`.`locale` = 'en'  ORDER BY `community_customizations`.`id` ASC LIMIT 1
  CommunityCustomization Load (0.4ms)  SELECT  `community_customizations`.* FROM `community_customizations` WHERE `community_customizations`.`community_id` = 1 AND `community_customizations`.`locale` = 'en'  ORDER BY `community_customizations`.`id` ASC LIMIT 1
  PaymentSettings Load (0.3ms)  SELECT  `payment_settings`.* FROM `payment_settings` WHERE `payment_settings`.`community_id` = 1 AND `payment_settings`.`active` = 1  ORDER BY `payment_settings`.`id` ASC LIMIT 1
   (0.5ms)  SELECT COUNT(*) AS count_all, priority AS priority FROM `delayed_jobs` WHERE (attempts < 3 AND run_at < '2016-03-17 01:28:13.852908') GROUP BY `delayed_jobs`.`priority`
  Listing Load (0.3ms)  SELECT  `listings`.* FROM `listings` WHERE `listings`.`id` = 123 LIMIT 1
  Person Load (0.4ms)  SELECT  `people`.* FROM `people` WHERE `people`.`id` = 'ad8xSIUpOr5yaa-dPlzTtY' LIMIT 1
  TransactionProcess Load (0.2ms)  SELECT  `transaction_processes`.* FROM `transaction_processes` WHERE `transaction_processes`.`community_id` = 1 AND `transaction_processes`.`id` = 3  ORDER BY `transaction_processes`.`id` ASC LIMIT 1
  Community Load (0.4ms)  SELECT  `communities`.* FROM `communities` WHERE `communities`.`id` = 1 LIMIT 1
  CACHE (0.0ms)  SELECT  `payment_settings`.* FROM `payment_settings` WHERE `payment_settings`.`community_id` = 1 AND `payment_settings`.`active` = 1  ORDER BY `payment_settings`.`id` ASC LIMIT 1  [["community_id", 1], ["active", true]]
  PaymentGateway Load (0.3ms)  SELECT  `payment_gateways`.* FROM `payment_gateways` WHERE `payment_gateways`.`community_id` = 1 LIMIT 1
   (0.2ms)  BEGIN
  SQL (0.5ms)  UPDATE `listings` SET `open` = 0, `updated_at` = '2016-03-17 01:28:14' WHERE `listings`.`id` = 123
   (1.6ms)  COMMIT
   (0.5ms)  SELECT COUNT(*) FROM `delayed_jobs` WHERE `delayed_jobs`.`handler` = '--- !ruby/object:ThinkingSphinx::Deltas::DelayedDelta::DeltaJob\nindex: listing_delta\n' AND `delayed_jobs`.`locked_at` IS NULL AND `delayed_jobs`.`failed_at` IS NULL
   (0.2ms)  BEGIN
  SQL (0.4ms)  INSERT INTO `delayed_jobs` (`priority`, `handler`, `run_at`, `created_at`, `updated_at`) VALUES (4, '--- !ruby/object:ThinkingSphinx::Deltas::DelayedDelta::FlagAsDeletedJob\nindex: listing_core\ndocument_id: 739\n', '2016-03-17 01:28:14', '2016-03-17 01:28:14', '2016-03-17 01:28:14')
   (1.5ms)  COMMIT
  Rendered listings/_listing_actions.haml (15.3ms)
  Rendered listings/_edit_profile_listing_links.haml (4.2ms)
  Rendered listings/_comment_form.haml (2.8ms)
  Rendered listings/close.js.erb (29.7ms)
   (0.2ms)  BEGIN
  SQL (2.5ms)  INSERT INTO `merit_actions` (`user_id`, `action_method`, `target_model`, `target_id`, `target_data`, `created_at`, `updated_at`) VALUES (0, 'close', 'listings', 123, '--- !ruby/object:Listing\nraw_attributes:\n  author_id: ad8xSIUpOr5yaa-dPlzTtY\n  transaction_process_id: 3\n  open: false\n  id: 123\n  delta: true\n  community_id: 1\n  category_old: \n  title: \'11\'\n  times_viewed: 0\n  language: \n  created_at: &7 2016-03-17 01:24:40.000000000 Z\n  updates_email_at: &8 2016-03-17 01:24:40.000000000 Z\n  updated_at: &10 2016-03-17 01:28:14.030977065 Z\n  last_modified: \n  sort_date: &9 2016-03-17 01:24:40.000000000 Z\n  listing_type_old: \n  description: \'\'\n  origin: \n  destination: \n  valid_until: \n  share_type_old: \n  privacy: private\n  comments_count: 0\n  subcategory_old: \n  old_category_id: \n  category_id: 2\n  share_type_id: \n  listing_shape_id: 3\n  shape_name_tr_key: 378df349-9339-41e7-9709-9e068137019d\n  action_button_tr_key: d6260e77-9c0c-43fd-821b-1c63e0579d56\n  organization_id: \n  price_cents: 0\n  currency: USD\n  quantity: \n  unit_type: \n  quantity_selector: \n  unit_tr_key: \n  unit_selector_tr_key: \n  deleted: 0\n  require_shipping_address: 0\n  pickup_enabled: 0\n  shipping_price_cents: \n  shipping_price_additional_cents: \n  payed_at: \nattributes: !ruby/object:ActiveRecord::AttributeSet\n  attributes: !ruby/object:ActiveRecord::LazyAttributeHash\n    types:\n      id: &1 !ruby/object:ActiveRecord::Type::Integer\n        precision: \n        scale: \n        limit: 4\n        range: !ruby/range\n          begin: -2147483648\n          end: 2147483648\n          excl: true\n      community_id: *1\n      author_id: &2 !ruby/object:ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter::MysqlString\n        precision: \n        scale: \n        limit: 255\n      category_old: *2\n      title: *2\n      times_viewed: *1\n      language: *2\n      created_at: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter\n        subtype: &3 !ruby/object:ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter::MysqlDateTime\n          precision: \n          scale: \n          limit: \n      updates_email_at: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter\n        subtype: *3\n      updated_at: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter\n        subtype: *3\n      last_modified: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter\n        subtype: *3\n      sort_date: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter\n        subtype: *3\n      listing_type_old: *2\n      description: &11 !ruby/object:ActiveRecord::Type::Text\n        precision: \n        scale: \n        limit: 65535\n      origin: *2\n      destination: *2\n      valid_until: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter\n        subtype: *3\n      delta: &4 !ruby/object:ActiveRecord::Type::Boolean\n        precision: \n        scale: \n        limit: 1\n      open: *4\n      share_type_old: *2\n      privacy: *2\n      comments_count: *1\n      subcategory_old: *2\n      old_category_id: *1\n      category_id: *1\n      share_type_id: *1\n      listing_shape_id: *1\n      transaction_process_id: *1\n      shape_name_tr_key: *2\n      action_button_tr_key: *2\n      organization_id: *1\n      price_cents: *1\n      currency: *2\n      quantity: *2\n      unit_type: &5 !ruby/object:ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter::MysqlString\n        precision: \n        scale: \n        limit: 32\n      quantity_selector: *5\n      unit_tr_key: &6 !ruby/object:ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter::MysqlString\n        precision: \n        scale: \n        limit: 64\n      unit_selector_tr_key: *6\n      deleted: *4\n      require_shipping_address: *4\n      pickup_enabled: *4\n      shipping_price_cents: *1\n      shipping_price_additional_cents: *1\n      payed_at: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter\n        subtype: *3\n    values:\n      id: 123\n      community_id: 1\n      author_id: ad8xSIUpOr5yaa-dPlzTtY\n      category_old: \n      title: \'11\'\n      times_viewed: 0\n      language: \n      created_at: *7\n      updates_email_at: *8\n      updated_at: 2016-03-17 01:24:40.000000000 Z\n      last_modified: \n      sort_date: *9\n      listing_type_old: \n      description: \'\'\n      origin: \n      destination: \n      valid_until: \n      delta: 1\n      open: 1\n      share_type_old: \n      privacy: private\n      comments_count: 0\n      subcategory_old: \n      old_category_id: \n      category_id: 2\n      share_type_id: \n      listing_shape_id: 3\n      transaction_process_id: 3\n      shape_name_tr_key: 378df349-9339-41e7-9709-9e068137019d\n      action_button_tr_key: d6260e77-9c0c-43fd-821b-1c63e0579d56\n      organization_id: \n      price_cents: 0\n      currency: USD\n      quantity: \n      unit_type: \n      quantity_selector: \n      unit_tr_key: \n      unit_selector_tr_key: \n      deleted: 0\n      require_shipping_address: 0\n      pickup_enabled: 0\n      shipping_price_cents: \n      shipping_price_additional_cents: \n      payed_at: \n    additional_types: {}\n    materialized: true\n    delegate_hash:\n      author_id: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: author_id\n        value_before_type_cast: ad8xSIUpOr5yaa-dPlzTtY\n        type: *2\n        value: ad8xSIUpOr5yaa-dPlzTtY\n      transaction_process_id: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: transaction_process_id\n        value_before_type_cast: 3\n        type: *1\n        value: 3\n      open: !ruby/object:ActiveRecord::Attribute::FromUser\n        name: open\n        value_before_type_cast: false\n        type: *4\n        value: false\n      id: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: id\n        value_before_type_cast: 123\n        type: *1\n        value: 123\n      delta: !ruby/object:ActiveRecord::Attribute::FromUser\n        name: delta\n        value_before_type_cast: true\n        type: *4\n        value: true\n      community_id: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: community_id\n        value_before_type_cast: 1\n        type: *1\n        value: 1\n      category_old: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: category_old\n        value_before_type_cast: \n        type: *2\n        value: \n      title: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: title\n        value_before_type_cast: \'11\'\n        type: *2\n        value: \'11\'\n      times_viewed: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: times_viewed\n        value_before_type_cast: 0\n        type: *1\n        value: 0\n      language: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: language\n        value_before_type_cast: \n        type: *2\n        value: \n      created_at: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: created_at\n        value_before_type_cast: *7\n        type: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter\n          subtype: *3\n        value: *7\n      updates_email_at: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: updates_email_at\n        value_before_type_cast: *8\n        type: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter\n          subtype: *3\n        value: *8\n      updated_at: !ruby/object:ActiveRecord::Attribute::FromUser\n        name: updated_at\n        value_before_type_cast: *10\n        type: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter\n          subtype: *3\n        value: *10\n      last_modified: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: last_modified\n        value_before_type_cast: \n        type: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter\n          subtype: *3\n        value: \n      sort_date: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: sort_date\n        value_before_type_cast: *9\n        type: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter\n          subtype: *3\n        value: *9\n      listing_type_old: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: listing_type_old\n        value_before_type_cast: \n        type: *2\n        value: \n      description: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: description\n        value_before_type_cast: \'\'\n        type: *11\n        value: \'\'\n      origin: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: origin\n        value_before_type_cast: \n        type: *2\n        value: \n      destination: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: destination\n        value_before_type_cast: \n        type: *2\n        value: \n      valid_until: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: valid_until\n        value_before_type_cast: \n        type: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter\n          subtype: *3\n        value: \n      share_type_old: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: share_type_old\n        value_before_type_cast: \n        type: *2\n        value: \n      privacy: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: privacy\n        value_before_type_cast: private\n        type: *2\n        value: private\n      comments_count: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: comments_count\n        value_before_type_cast: 0\n        type: *1\n        value: 0\n      subcategory_old: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: subcategory_old\n        value_before_type_cast: \n        type: *2\n        value: \n      old_category_id: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: old_category_id\n        value_before_type_cast: \n        type: *1\n        value: \n      category_id: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: category_id\n        value_before_type_cast: 2\n        type: *1\n        value: 2\n      share_type_id: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: share_type_id\n        value_before_type_cast: \n        type: *1\n        value: \n      listing_shape_id: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: listing_shape_id\n        value_before_type_cast: 3\n        type: *1\n        value: 3\n      shape_name_tr_key: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: shape_name_tr_key\n        value_before_type_cast: 378df349-9339-41e7-9709-9e068137019d\n        type: *2\n        value: 378df349-9339-41e7-9709-9e068137019d\n      action_button_tr_key: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: action_button_tr_key\n        value_before_type_cast: d6260e77-9c0c-43fd-821b-1c63e0579d56\n        type: *2\n        value: d6260e77-9c0c-43fd-821b-1c63e0579d56\n      organization_id: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: organization_id\n        value_before_type_cast: \n        type: *1\n        value: \n      price_cents: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: price_cents\n        value_before_type_cast: 0\n        type: *1\n        value: 0\n      currency: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: currency\n        value_before_type_cast: USD\n        type: *2\n        value: USD\n      quantity: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: quantity\n        value_before_type_cast: \n        type: *2\n        value: \n      unit_type: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: unit_type\n        value_before_type_cast: \n        type: *5\n        value: \n      quantity_selector: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: quantity_selector\n        value_before_type_cast: \n        type: *5\n        value: \n      unit_tr_key: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: unit_tr_key\n        value_before_type_cast: \n        type: *6\n        value: \n      unit_selector_tr_key: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: unit_selector_tr_key\n        value_before_type_cast: \n        type: *6\n        value: \n      deleted: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: deleted\n        value_before_type_cast: 0\n        type: *4\n        value: false\n      require_shipping_address: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: require_shipping_address\n        value_before_type_cast: 0\n        type: *4\n        value: false\n      pickup_enabled: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: pickup_enabled\n        value_before_type_cast: 0\n        type: *4\n        value: false\n      shipping_price_cents: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: shipping_price_cents\n        value_before_type_cast: \n        type: *1\n        value: \n      shipping_price_additional_cents: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: shipping_price_additional_cents\n        value_before_type_cast: \n        type: *1\n        value: \n      payed_at: !ruby/object:ActiveRecord::Attribute::FromDatabase\n        name: payed_at\n        value_before_type_cast: \n        type: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter\n          subtype: *3\n        value: \nnew_record: false\nactive_record_yaml_version: 0\n', '2016-03-17 01:28:14', '2016-03-17 01:28:14')
   (1.6ms)  COMMIT
  Merit::Action Load (0.5ms)  SELECT `merit_actions`.* FROM `merit_actions` WHERE `merit_actions`.`processed` = 0
   (0.1ms)  BEGIN
  SQL (0.3ms)  UPDATE `merit_actions` SET `processed` = 1, `updated_at` = '2016-03-17 01:28:14' WHERE `merit_actions`.`id` = 27
   (1.5ms)  COMMIT
  Person Load (0.4ms)  SELECT  `people`.* FROM `people` WHERE `people`.`id` = '123' LIMIT 1
  CACHE (0.0ms)  SELECT  `people`.* FROM `people` WHERE `people`.`id` = '123' LIMIT 1  [["id", 123]]
[merit] Couldn't find model to grant reputation to. Refer to https://github.com/tute/merit/issues/171#issuecomment-44185696.
Completed 200 OK in 4267ms (Views: 37.3ms | ActiveRecord: 27.4ms)
   (0.2ms)  BEGIN
   (0.2ms)  COMMIT

**Comment by tute** [comment] 2016-03-17 01:32
That one worked. I'll need everything though, starting from the request and path, and controller that serves the action.

**Comment by top1select** [comment] 2016-03-17 01:34
Started PUT "/en/admin/listings/123-11/close" for 38.124.107.91 at 2016-03-16 21:28:09 -0400
Cannot render console from 38.124.107.91! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by ListingsController#close as JS
  Parameters: {"locale"=>"en", "person_id"=>"admin", "id"=>"123-11"}
/home/ec2-user/sharetribe/app/models/community.rb:244: warning: duplicated key at line 245 ignored: :favicon
  Community Load (0.5ms)  SELECT  `communities`.* FROM `communities` WHERE `communities`.`ident` = 'dev'  ORDER BY `communities`.`id` ASC LIMIT 1
   (0.2ms)  SELECT COUNT(*) FROM `communities`
  Community Load (0.3ms)  SELECT  `communities`.* FROM `communities`  ORDER BY `communities`.`id` ASC LIMIT 1
  CACHE (0.0ms)  SELECT COUNT(*) FROM `communities`
  ActiveRecord::SessionStore::Session Load (0.4ms)  SELECT  `sessions`.* FROM `sessions` WHERE `sessions`.`session_id` = 'a555c11388335b4eb9a917691f22696f'  ORDER BY `sessions`.`id` ASC LIMIT 1
  Person Load (0.3ms)  SELECT  `people`.* FROM `people` WHERE `people`.`id` = 'ad8xSIUpOr5yaa-dPlzTtY'  ORDER BY `people`.`id` ASC LIMIT 1
  CommunityMembership Load (0.4ms)  SELECT  `community_memberships`.* FROM `community_memberships` WHERE `community_memberships`.`person_id` = 'ad8xSIUpOr5yaa-dPlzTtY' AND `community_memberships`.`community_id` = 1 AND `community_memberships`.`status` = 'accepted'  ORDER BY `community_memberships`.`id` ASC LIMIT 1

**Comment by tute** [comment] 2016-03-17 01:35
That's another route: `/admin\/listings\/\d+-\d+\/close`

**Comment by tute** [comment] 2016-03-17 01:36
You have to match the string after `Started HTTP_ACTION "path_to_match"`

**Comment by tute** [comment] 2016-03-17 01:37
And the method name in `Processing by CONTROLLER#METHOD_NAME as`

**Comment by top1select** [comment] 2016-03-17 01:37
You meant this route? What should be the rule for it? 

`PUT      (/:locale)/:person_id/listings/:id/close(.:format)     listings#close`

**Comment by tute** [comment] 2016-03-17 01:39
It's whichever route you want the reputation to be granted. If it's https://github.com/merit-gem/merit/issues/248#issuecomment-197638760, then it will be inside of `admin/`.

**Comment by top1select** [comment] 2016-03-17 01:42
But admin is only the user id, it can be anything else, like user1, user2 for person_id, I just named the user admin.

PUT (/:locale)/:**person_id**/listings/:id/close(.:format) listings#close

**Comment by top1select** [comment] 2016-03-17 01:44
Will this rule work?

score -1, :on => 'person_id/listings#close', model_name: 'Person', to: ::person

**Comment by tute** [comment] 2016-03-17 01:47
In your log it says: `Started PUT "/en/admin/listings/123-11/close" for 38.124.107.91 at 2016-03-16 21:28:09 -0400`.

It begins with `admin/`. In https://github.com/merit-gem/merit/blob/master/lib/merit/rules_matcher.rb#L10 you can see that we match a regular expression from the beginning of the string (which in turn makes me wonder if you need to take the locale into account).

**Comment by top1select** [comment] 2016-03-17 01:53
I see, but this rule does generate a record in merit_actions, the only part missing is the wrong person id, 123 is the listing id, not the person id:

`score -1, :on => 'person_id/listings#close', model_name: 'Person', to: :person
`


 Merit::Action Load (0.4ms)  SELECT `merit_actions`.* FROM `merit_actions` WHERE 
   (1.6ms)  COMMIT
.....
  Person Load (0.3ms)  SELECT  `people`.* FROM `people` **WHERE `people`.`id` = '123'** LIMIT 1

**Comment by tute** [comment] 2016-03-17 02:13
`'person_id/listings#close'` will try to literally match the `person_id` string. For that route it would be something like:

```ruby
score 1, on: /\d+\/listings\/\d+/\/close#close/`
```

And with that I go to sleep. I'll close this issue as it's not a bug in the library, feel free to continue asking questions. You might want to publish them in StackOverflow too, so you don't rely on the chance of finding me available.

Best!

**Closed by tute** 2016-03-17 02:13 UTC
Labels: question/discussion

**Comment by top1select** [comment] 2016-03-17 02:15
Thanks a lot, tute, really appreciated!
