### ISSUE TITLE
Leaderboard?

### ISSUE THREAD

**Issue by monroemann** [merit-gem/merit#322] opened 2019-04-15 02:02 UTC
Hello!

We are trying to add a leaderboard page, but this code:
```
  def leaderboard
    leaderboard = Merit::Score.top_scored(since_date: 1.week.ago, limit: 25)    
  end
```
This results in a 'undefined method top_score error.

We also tried to manually create a leaderboard by creating an array, i.e.

```
leaderboard = User.all.score_points(category: 'Total')
```
but that also resulted in an undefined method, this time for score_points

Do you happen to know what we are doing incorrectly?  Thank you!

**Comment by monroemann** [comment] 2019-04-15 02:04
@tute thank you! :D

**Comment by tute** [comment] 2019-04-15 12:44
Hi @monroemann! You have to define that method in a new file in your Rails app, copying the contents from https://github.com/merit-gem/merit/wiki/How-to-show-a-points-leaderboard. You can do it in a model or an initializer and it will work (the wiki suggests an initializer but I'd now do it within `app/models/merit/`).

Best!

**Comment by monroemann** [comment] 2019-04-15 16:06
Hi @tute thanks for the quick response!  Two follow ups:
1. So I should create a file called app/models/merit/merit_scores_override.rb or just take that code and insert it directly into an already existing file?
2. If we want to list only users with more than 50 points earned over last 7 days, is that possible? This one would be for admin, so we know who is an “active user”. 

Thanks very much!

**Comment by tute** [comment] 2019-04-15 18:32
1. It would be a new file called `app/models/merit/score.rb`
2. Have to recheck the script, not exactly sure now but should be possible!

:)

**Comment by monroemann** [comment] 2019-04-16 17:13
Hi @tute Thanks again for your generous assistance!

We created the app/models/merit/score.rb file and pasted the code you listed on https://github.com/merit-gem/merit/wiki/How-to-show-a-points-leaderboard

And then, I put this code in the view:

<%= Merit::Score.top_scored %>

I reset the server and went to the leaderboard page and I'm still getting the same error:

`undefined method `top_scored' for Merit::Score(id: integer, sash_id: integer, category: string):Class`

Is there still something I may be missing?  Thanks!

**Comment by tute** [comment] 2019-04-16 19:53
:thinking: And does putting it as an initializer work?

**Comment by monroemann** [comment] 2019-04-21 20:29
I shall try that @tute

**Comment by monroemann** [comment] 2019-04-21 20:36
Doing that gives me this:

![image](https://user-images.githubusercontent.com/23728446/56475216-86e92400-6453-11e9-8ee9-60a6477a25f1.png)

So it seems to be accessing something in the database, but it's not a leaderboard.  Does this look like we're on the right track? 

The view code is: <%= Merit::Score.top_scored %>

Is that an array it is displaying?

**Comment by monroemann** [comment] 2019-04-21 20:42
Ahh, it's a hash.  I am getting closer: 
![image](https://user-images.githubusercontent.com/23728446/56475315-6077b880-6454-11e9-8779-c48f958b2d57.png)

I'm working on displaying the user's name, and the point value.

**Comment by monroemann** [comment] 2019-04-21 20:52
I'm getting closer.  I was able to map them to just display user_id and sum_points.  But I'm stuck on how to then access that user_id to turn it into the user's .full_name (which is a method we defined).  

![image](https://user-images.githubusercontent.com/23728446/56475403-cadd2880-6455-11e9-936e-f6e57b902c24.png)

**Comment by monroemann** [comment] 2019-04-21 21:02
```
      <% Merit::Score.top_scored.map.each do |x|  %>
        <% array = [] %>
        <% array = x.values[0] %>
        <% i = 0 %>
          <% while i < x.length %>
            <%= User.find(user_id: array[i]).first_name %>
            <% i += 1 %>
          <% end %>
      <% end %>
```
This is what I am working on, but I think I'm probably making it too complicated.

**Comment by monroemann** [comment] 2019-04-21 21:12
Progress:
```
      <% Merit::Score.top_scored.map.each do |x|  %>
        <% array = [] %>
          <% x.each do |user| %>
            <% array << x.values[0] %>
          <% end %>
        <% i = 0 %>
          <% while i < x.size %>
            <%= User.find(array[i]).first_name %>
            <% i += 1 %>
          <% end %>
      <% end %>
```
give this output:
![image](https://user-images.githubusercontent.com/23728446/56475618-9d45ae80-6458-11e9-9a7d-1694cfaf6d90.png)

Trying to figure out why there are duplicates.  

I guess I'll stop at this point.  Is there an easier way to display the leaderboard? 😄

**Comment by tute** [comment] 2019-04-22 14:29
I think you'd want something like:

```erb
<%= Merit::Score.top_scored.map do |top_score_hash|
  User.find(top_score_hash[:user_id]).first_name
end.to_sentence %>
```

Closing this issue as it's not a bug in merit or its docs, but happy to continue further discussion. Good luck!

**Closed** 2019-04-22 14:29 UTC

**Comment by monroemann** [comment] 2019-04-22 19:13
Hi @tute Sorry to bother you again, but I'm getting this error:

![image](https://user-images.githubusercontent.com/23728446/56519898-1bfe2280-6511-11e9-99eb-2908024c4589.png)

Thoughts?

**Comment by monroemann** [comment] 2019-04-22 19:13
And does this only show the first name?  Is the score also included in this code?

**Comment by tute** [comment] 2019-04-23 17:09
`top_score_hash` should have the score, too. To debug, what does the following show for you?

```
<%= p Merit::Score.top_scored.map(&:inspect).inspect %>
<%= p Merit::Score.top_scored.inspect %>
```

**Comment by monroemann** [comment] 2019-04-23 18:10
Hi @tute 

Here is the output from each of those lines of code, separated by two line breaks:

![image](https://user-images.githubusercontent.com/23728446/56605194-8d050f00-65d1-11e9-9345-aea91d2753e8.png)

Does this help you?

**Comment by tute** [comment] 2019-04-23 18:38
Yes, and it might help you too! The keys are strings not symbols so:

```ruby
<%= Merit::Score.top_scored.map do |top_score_hash|
  User.find(top_score_hash["user_id"]).first_name + " " + top_score_hash["sum_points"]
end.to_sentence %>
```

**Comment by monroemann** [comment] 2019-04-23 19:05
Another error! 😄 

![image](https://user-images.githubusercontent.com/23728446/56608616-2b48a300-65d9-11e9-9e59-cb3b35d11c93.png)

Thoughts on this one @tute

**Comment by monroemann** [comment] 2019-04-23 19:06
Do we need to turn sum_points into a string?  Or maybe I'll just try displaying it without quotation marks?

**Comment by monroemann** [comment] 2019-04-23 19:09
I found this, but it's not quite clear to me: https://stackoverflow.com/questions/20450497/ruby-on-rails-no-implicit-conversion-of-string-into-integer-for-getting-json

**Comment by monroemann** [comment] 2019-04-23 19:16
Ahh!  I got it work by adding .to_s !!

 ```
<%= Merit::Score.top_scored.map do |top_score_hash|
        User.find(top_score_hash["user_id"]).first_name + " " + top_score_hash["sum_points"]**.to_s**
  end.to_sentence %>
```
That produces this:
![image](https://user-images.githubusercontent.com/23728446/56609161-70210980-65da-11e9-8814-f9fa412bb08c.png)

My final questions: how to display them in distinct columns.  Can I just do two different User.find queries, each displayed within a different column?  Or better, perhaps I should move these queries into the controller or model, and save the results as instance variables?  Thanks so much @tute

**Comment by tute** [comment] 2019-04-23 19:22
I wish we were closer so we could pair in a meetup, I think it will be way easier for you to grasp this in a collaborative space like that.

No need of another find, as you already have the score. The line in the middle of my snippet contains the data you need, you may now display it as you please in an erb template.

Best!

**Comment by monroemann** [comment] 2019-04-23 19:26
HOORAY!  I got it to work!  This is the code I wrote:

![image](https://user-images.githubusercontent.com/23728446/56609849-20434200-65dc-11e9-96e1-63d8efbc2e5c.png)

And this is the result.  Not bad, do you agree?

![image](https://user-images.githubusercontent.com/23728446/56609880-3224e500-65dc-11e9-887f-857a3ffc233a.png)

Does this look like it works okay?

**Comment by monroemann** [comment] 2019-04-23 19:30
Follow up question: If on this one page, I'd like to display four leaderboards:
Today, Last 7 Days, Last 30 days, and Last 365 days, can I manually override that here in the view?  Or do I have to do something in that initializer file?

**Comment by monroemann** [comment] 2019-04-23 19:37
I just looked at your documentation again.  Would this work appropriately: 

```
        <% Merit::Score.top_scored(since_date: 1.week.ago,
        limit: 25).map do |top_score_hash| %>
```

**Comment by monroemann** [comment] 2019-04-23 19:37
> 
> 
> I wish we were closer so we could pair in a meetup, I think it will be way easier for you to grasp this in a collaborative space like that.
> 
> No need of another find, as you already have the score. The line in the middle of my snippet contains the data you need, you may now display it as you please in an erb template.
> 
> Best!

We shall meet one day in person! :smile:

**Comment by monroemann** [comment] 2019-04-23 19:41
And, it worked!  Looks like this:

![image](https://user-images.githubusercontent.com/23728446/56610735-276b4f80-65de-11e9-903c-8242acae98f2.png)

Is it okay that I have all that code in the erb template?

**Comment by monroemann** [comment] 2019-04-23 19:43
And (thanks for being so patient with all my questions), is there a way to show "This Month", "This Week", "This Year", etc that uses the calendar?  And what exactly does 1.day.ago do?  Does that show today, or the last 24 hours?  It would be great to show 'Today' and 'Yesterday' based on clock time.

**Comment by tute** [comment] 2019-04-23 19:45
Glad you made it work! Check Rails' DateTime API:

- https://www.rubydoc.info/docs/rails/DateTime
- https://www.rubydoc.info/docs/rails/DateTime:at_beginning_of_day

**Comment by monroemann** [comment] 2019-04-24 00:36
Thank you very much!   Shall start researching!  😄 🚀

**Comment by monroemann** [comment] 2019-04-24 00:36
Where do you live, incidentally?  You are Argentinian?
