### ISSUE TITLE
How to create activity_log after point rules triggered?

### ISSUE THREAD

**Issue by energypantry** [merit-gem/merit#315] opened 2018-12-28 09:57 UTC
I use 2.4.0 in my app because the rails version is 3.2.9.

when user.add_point is executed, but there was no activity_log created, I thought the activity_log could be created automatically

**Comment by tute** [comment] 2019-03-17 21:55
Hey @energypantry. The `ActivityLog` is updated automatically when you use the `grant_on` or `score` APIs. Internally, the `Judge` takes care of those rules, and updates observers in https://github.com/merit-gem/merit/blob/master/lib/merit/judge.rb#L29-L33, calling then `Merit::ReputationChangeObserver`.

It's an open question for me now whether we should move the observer updates from `Judge` to `add_point` instead, but for now it doesn't work that way.

**Comment by tute** [comment] 2019-03-17 21:58
Related with https://github.com/merit-gem/merit/issues/305

**Comment by tute** [comment] 2020-08-15 10:38
Closing as a duplicate of issue 305. Thanks for reporting.

**Closed by tute** 2020-08-15 10:38 UTC
Labels: new feature?
