### ISSUE TITLE
warning: already initialized constant Merit::AppBadgeRules

### ISSUE THREAD

**Issue by emaillenin** [merit-gem/merit#173] opened 2014-06-02 04:23 UTC
I get the following error while initializing rails console/server while using Merit ~> 2.0. The same warning existing since Merit 2.0.0.

```
~/project (master) ⚡ rails c
/Library/Ruby/Gems/2.0.0/gems/merit-2.1.1/lib/merit.rb:83: warning: already initialized constant Merit::AppBadgeRules
/Library/Ruby/Gems/2.0.0/gems/merit-2.1.1/lib/merit.rb:83: warning: previous definition of AppBadgeRules was here
/Library/Ruby/Gems/2.0.0/gems/merit-2.1.1/lib/merit.rb:84: warning: already initialized constant Merit::AppPointRules
/Library/Ruby/Gems/2.0.0/gems/merit-2.1.1/lib/merit.rb:84: warning: previous definition of AppPointRules was here
Loading development environment (Rails 4.0.0)
```

**Comment by beydogan** [comment] 2015-07-15 17:14
I'm getting the same warning message.

```
merit (2.3.2)
rails (4.1.6)
rails-api (0.4.0)
```

**Comment by TravisTam** [comment] 2016-02-13 09:04
getting same warning.

**Comment by domness** [comment] 2016-02-17 15:04
Getting the same warning as well:

```
gems/merit-2.3.2/lib/merit.rb:88: warning: already initialized constant Merit::AppBadgeRules
gems/merit-2.3.2/lib/merit.rb:88: warning: previous definition of AppBadgeRules was here
gems/merit-2.3.2/lib/merit.rb:89: warning: already initialized constant Merit::AppPointRules
gems/merit-2.3.2/lib/merit.rb:89: warning: previous definition of AppPointRules was here
```

Ruby 2.2.3
Rails 4.2.5

**Comment by tute** [comment] 2016-02-24 23:48
I wonder why would we hit `ActiveSupport.on_load(:action_controller)` more than once on server initialization. @eileencodes, can you spot why is this happening? Thank you very much!

**Comment by zokioki** [comment] 2016-03-14 21:38
I'm seeing this warning as well:

- Merit 2.3.3
- Ruby 2.3.0
- Rails 5.0.0.beta3

**Comment by pacMakaveli** [comment] 2016-05-25 11:03
In reply to @zokioki which has a very similar setup with mine. I'm not getting this problem

- Merit - 2.3.4
- Ruby 2.3.1-p112
- Rails 5.0.0.rc1

There is a problem with Ruby 2.3.0, so you might want to update to 2.3.1
https://github.com/e2/ruby_dep/issues/8#issuecomment-217320375

**Comment by zokioki** [comment] 2016-05-28 01:18
@pacMakaveli I've updated Ruby, Merit and Rails to exactly match the versions in your setup - the problem persists for me.

**Comment by pacMakaveli** [comment] 2016-05-28 08:39
@zokioki Did you update you bin/* ?
Rails 5 introduced a new way of loading the files. http://railsdiff.org/5.0.0.beta3/5.0.0.rc1

Be sure to check *config.ru* , *bin/** and *application.rb*

**Comment by zokioki** [comment] 2016-05-30 01:04
@pacMakaveli Updating the code highlighted in that railsdiff for the rc1 release did the trick for me. Thank you! 👍

**Comment by jrasanen** [comment] 2016-07-14 08:49
Changing the highlighted code didn't work for me, I still keep getting the same errors, @emaillenin's fix would work for me, my stacktrace is nearly identical when attaching binding.pry.


**Trace**
```ruby
/Users/jrasanen/.rvm/gems/ruby-2.3.1/gems/merit-2.3.4/lib/merit.rb:87:in `block (2 levels) in <class:Engine>'
/Users/jrasanen/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
/Users/jrasanen/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
/Users/jrasanen/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
/Users/jrasanen/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:27:in `each'
/Users/jrasanen/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
/Users/jrasanen/.rvm/gems/ruby-2.3.1/gems/merit-2.3.4/lib/merit.rb:85:in `block in <class:Engine>'
/Users/jrasanen/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `instance_exec'
/Users/jrasanen/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `run'
/Users/jrasanen/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/jrasanen/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
/Users/jrasanen/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/Users/jrasanen/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
/Users/jrasanen/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
/Users/jrasanen/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
/Users/jrasanen/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
/Users/jrasanen/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
/Users/jrasanen/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
/Users/jrasanen/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
/Users/jrasanen/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/initializable.rb:54:in `run_initializers'
/Users/jrasanen/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/application.rb:352:in `initialize!'
/Users/jrasanen/Development/ror/stream/s/config/environment.rb:5:in `<top (required)>'
/Users/jrasanen/Development/ror/stream/s/config.ru:2:in `require_relative'
/Users/jrasanen/Development/ror/stream/s/config.ru:2:in `block in <main>'
/Users/jrasanen/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
/Users/jrasanen/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
/Users/jrasanen/Development/ror/stream/s/config.ru:in `new'
/Users/jrasanen/Development/ror/stream/s/config.ru:in `<main>'
/Users/jrasanen/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
/Users/jrasanen/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
/Users/jrasanen/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
/Users/jrasanen/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/server.rb:318:in `build_app_and_options_from_config'
/Users/jrasanen/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/server.rb:218:in `app'
/Users/jrasanen/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/server.rb:59:in `app'
/Users/jrasanen/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/server.rb:353:in `wrapped_app'
/Users/jrasanen/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/server.rb:124:in `log_to_stdout'
/Users/jrasanen/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/server.rb:77:in `start'
/Users/jrasanen/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:90:in `block in server'
/Users/jrasanen/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:85:in `tap'
/Users/jrasanen/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:85:in `server'
/Users/jrasanen/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
/Users/jrasanen/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<top (required)>'
```

**config.ru**
```ruby
# This file is used by Rack-based servers to start the application.
require_relative 'config/environment'

run Rails.application
```

**application.rb**
```ruby
require_relative 'boot'

require 'rails/all'

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module S
  class Application < Rails::Application
    # redacted~
  end
end
```

**environment.rb**
```ruby
# Load the Rails application.
require_relative 'application'

# Initialize the Rails application.
Rails.application.initialize!
```


**bin/rails**
```ruby
#!/usr/bin/env ruby
APP_PATH = File.expand_path('../config/application', __dir__)
require_relative '../config/boot'
require 'rails/commands'
```

**Comment by redtachyons** [comment] 2017-11-01 02:24
@zokioki Can you please explain what exactly is changed? I am still getting this error

**Comment by redtachyons** [comment] 2017-11-01 02:26
ActiveSupport.on_load(:action_controller) is getting called twice , So I don't think this issue is specific to this gem

**Comment by redtachyons** [comment] 2017-11-01 03:18
After digging more I found the cause, rails calls `ActiveSupport.run_load_hooks(:action_controller, self)` From two places, one from ActionController::Base and other from ActionController::API, If your app or the gems you use load both, then `action_controller` load callback will load twice 

1. https://github.com/rails/rails/blob/5-1-stable/actionpack/lib/action_controller/base.rb#L271

2. https://github.com/rails/rails/blob/5-1-stable/actionpack/lib/action_controller/api.rb#L145

**Comment by redtachyons** [comment] 2017-11-03 16:25
@tute opened an issue [here](https://github.com/rails/rails/issues/31041) please have a look

**Comment by tute** [comment] 2017-11-03 18:32
Thank you @redtachyons! It looks like the `:run_once` option would fix our case, as Rafael mentions in https://github.com/rails/rails/issues/31041#issuecomment-341763576; we don't care about the type of controller on this part of merit. That's introduced in https://github.com/rails/rails/pull/30045 though, already for Rails 5.1? How does Rails 5 react if we try to use the option but it doesn't yet exist?

Thank you again!

**Comment by redtachyons** [comment] 2017-11-03 18:57
Thanks for the reply, I tried https://gist.github.com/redtachyons/568e0f79804d80f90de12f73353a86a2 this snippet with rails >5.0 & < 5.1.4, it just silently ignored that extra parameter. So adding `run_once` will fix the issue for newer version of rails

**Comment by tute** [comment] 2017-11-03 19:02
Sounds like finally we have a proper solution! Mind sending in a PR?

**Comment by redtachyons** [comment] 2017-11-03 19:02
Sure

**Comment by tute** [comment] 2017-11-03 19:13
Closing in favor of https://github.com/merit-gem/merit/pull/282. Thank you, @redtachyons! ❤️

**Closed by tute** 2017-11-03 19:13 UTC
Labels: help wanted

**Comment by natanio** [comment] 2022-01-14 17:10
I'm seeing this in our app in the console output of `rails jobs:work` using `DelayedJob`.

merit (4.0.2)
ruby 2.7.4p191
ails (6.1.4.4)

```
/merit/lib/merit.rb:70: warning: already initialized constant Merit::AppPointRules
/merit/lib/merit.rb:70: warning: previous definition of AppPointRules was here
```

Adjusting this locally has removed seeing the above warnings: https://github.com/merit-gem/merit/issues/173#issuecomment-44801342.
