### ISSUE TITLE
What if you don't have a controller resource

### ISSUE THREAD

**Issue by rjrobinson** [merit-gem/merit#311] opened 2018-10-20 20:08 UTC
I am using GraphQL for my API, is there a way to bypass the controller requirement, or do I just map it to the main controller.

**Comment by tute** [comment] 2018-10-21 00:03
If you can't hook to HTTP requests to controllers, you can use the `add_badge` manually where it makes sense: https://github.com/merit-gem/merit#other-actions.

I'll close this issue as it's not a bug, but happy to continue helping! :+1:

**Closed by tute** 2018-10-21 00:03 UTC

**Comment by jesster2k10** [comment] 2020-04-11 18:22
Hey there could you provide more clarity on the significance of the controller action? If I were to map all y `grant_on` to one controller, would that make a difference? The reason why is that with GraphQL you really only have on controller - `graphql_controller` and one action - `execute` and everything else is handled with resolvers/mutations.

So if I wanted to use this library with GraphQL, and I didn't want to manually add the badges, is that the best way?

**Comment by tute** [comment] 2020-04-13 10:29
`merit` doesn't have hooks for GraphQL APIs as of now. Mapping all `grant_on`s to that single action might work well for you indeed.

**Comment by jesster2k10** [comment] 2020-04-13 22:01
> `merit` doesn't have hooks for GraphQL APIs as of now. Mapping all `grant_on`s to that single action might work well for you indeed.

Are there any specific drawbacks to this setup or would it work as it would a standard REST api?

**Comment by tute** [comment] 2020-04-13 23:12
You may need more verbose configurations to figure out what object you are working with. Maybe using `add_badge` syntax in mutations ends up being simpler for you? Not sure, as I never tried it myself. But you'll know from first-hand experience. Please post your findings!
