### ISSUE TITLE
Example apps?

### ISSUE THREAD

**Issue by seanfcarroll** [merit-gem/merit#307] opened 2018-09-18 09:13 UTC
I've found one [example app](https://github.com/pete2786/mnw-rails4) for Merit, based on a [blog post](http://pete2786.github.io/2015/07/05/merit-gem.html).

Are there any other examples of projects using Merit? I'm happy to compile them into a Wiki page.

**Comment by redtachyons** [comment] 2018-09-18 09:34
You can find some using GitHub dependency graph https://github.com/merit-gem/merit/network/dependents

**Comment by tute** [comment] 2018-09-18 12:12
There is also the test dummy app: https://github.com/merit-gem/merit/tree/master/test/dummy

Closing as it's not a bug in merit, but happy to continue discussing.

**Closed by tute** 2018-09-18 12:12 UTC

**Comment by seanfcarroll** [comment] 2018-09-18 12:14
Thanks @tute, I missed the dummy app. It's an awesome gem and I'd be happy to describe our final implementation on the wiki when it is ready ... we will have a few edge cases. I'll open further such questions on SO.

**Comment by tute** [comment] 2018-09-18 12:15
Awesome, thanks! Today I learned about that blog post too, documentation in blog posts is helpful too. I'll receive notifications for StackOverflow questions. Best!

**Comment by adrienpoly** [comment] 2018-11-14 20:32
👋 @seanfcarroll 
I was looking for examples on how to test with Rspec Merit Gem and looked into your project. Thanks helped me a lot.

Anyone looking into this can have a look at this great project as a reference on how to test:
https://github.com/crowdAI/crowdai/tree/master/spec/badges

**Comment by seanfcarroll** [comment] 2018-11-14 20:34
Thanks @adrienpoly, it will probably me pushed into production this week.
