### ISSUE TITLE
Issue with reconfirmation of email address

### ISSUE THREAD

**Issue by monroemann** [merit-gem/merit#328] opened 2019-06-09 15:27 UTC
@tute First, thanks again for your awesome gem.  It really helps us out a lot.

Second, it worked perfectly up until one week ago.  It seems after we just set up email reconfirmation, but now, on production, it totally has prevented the merit gem from working, but only for new users who used the email reconfirmation.  Once we comment out the email reconfirmation code, the merit gem starts working again for everyone.  Here is the relevant code.  I was wondering if anything jumps out at you that is causing the conflict with merit:

![image](https://user-images.githubusercontent.com/23728446/59160881-38e2bb00-8aa9-11e9-91f9-edef26c36ac0.png)
![image](https://user-images.githubusercontent.com/23728446/59160887-48620400-8aa9-11e9-9e65-2b92223c1d03.png)
![image](https://user-images.githubusercontent.com/23728446/59160892-56b02000-8aa9-11e9-97da-0fdab5720783.png)
![image](https://user-images.githubusercontent.com/23728446/59160896-629be200-8aa9-11e9-8bc9-a92a5c84ca45.png)
![image](https://user-images.githubusercontent.com/23728446/59160901-75161b80-8aa9-11e9-828d-099d41e484e3.png)

**Comment by tute** [comment] 2019-06-10 03:00
I think you want to add the `on: :create` option to the `email_confirmation` validation in the `User` model

**Comment by monroemann** [comment] 2019-06-10 15:39
@tute Hooray!  Yes, that got the merit gem working again for new members.  What does the `on: :create` code do?

However, we still have one issue: will this also allow the merit gem to work for those members who joined prior to our fixing this bug?  Or do we have to manually fix those members somehow, and if so, what must we do manually to allow each of those 5 members access the merit gem too?

Thanks so much!

**Comment by bhavyabh** [comment] 2019-06-10 16:25
@tute, I am working with @monroemann on this isuue.  Thanks for this great gem & support.

**Comment by Shab12345** [comment] 2019-06-10 16:33
> @tute, I am working with @monroemann on this isuue. Thanks for this great gem & support.

Following :+1:

**Comment by monroemann** [comment] 2019-06-11 14:25
@bhavyabh @Shab12345 I believe we have confirmed that the fix @tute provided is also retroactive to those members for whom merit stopped working.  Can one of you please confirm?

**Comment by tute** [comment] 2019-07-28 20:09
Closing this issue as it's not a bug in merit, but happy to continue further discussion here.

Previously created users should be fine indeed!

**Closed by tute** 2019-07-28 20:10 UTC
